def BGS_scraper (datee, datea, commodity) :
  url = f"https://www2.bgs.ac.uk/mineralsuk/statistics/wms.cfc?method=listResults&dataType=Production&dateFrom={datea}&dateTo={datee}&commodity={commodity}&country=&agreeToTsAndCs=agreed&exportToSpreadsheet=Yes"
  urllib.request.urlretrieve(url, "test.xlsx")
  df = pd.read_excel('test.xlsx', header = 1) 
  df = df[['\n\tCountry',
             'Unnamed: 3',
             'Unnamed: 5',
             'Unnamed: 7',
             'Unnamed: 9',
             'Unnamed: 11',
             'Unnamed: 13',
             'Unnamed: 15',
             'Unnamed: 17',
             'Unnamed: 19',
             'Unnamed: 21',
             'Unnamed: 23',
             ]]
  df = df.rename(columns={
             '\n\tCountry': 'Pays',
             'Unnamed: 3':f'{datea}',
             'Unnamed: 5':f'{datea+1}',
             'Unnamed: 7':f'{datea+2}',
             'Unnamed: 9':f'{datea+3}',
             'Unnamed: 11':f'{datea+4}',
             'Unnamed: 13':f'{datea+5}',
             'Unnamed: 15':f'{datea+6}',
             'Unnamed: 17':f'{datea+7}',
             'Unnamed: 19':f'{datea+8}',
             'Unnamed: 21':f'{datea+9}',
             'Unnamed: 23':f'{datea+10}',
             })
  df = df[df['Pays'].isin(options)]
  df= df.T
  new_header = df.iloc[0] #grab the first row for the header
  df = df[1:] #take the data less the header row
  df.columns = new_header
  return df 




options = [
 'Algeria',
 'Angola',
 'Benin',
 'Botswana',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Cape Verde',
 'Central African Republic',
 'Chad',
 'Congo, Democratic Republic',
 'Congo, Rep.',
 "Cote d'Ivoire",
 'Egypt',
 'Equatorial Guinea',
 'Eritrea',
 'Eswatini',
 'Ethiopia',
 'Gabon',
 'Ghana',
 'Guinea',
 'Kenya',
 'Lesotho',
 'Liberia',
 'Libya',
 'Madagascar',
 'Malawi',
 'Mauritania',
 'Mauritius',
 'Morocco',
 'Mozambique',
 'Namibia',
 'Niger',
 'Nigeria',
 'Rwanda',
 'Senegal',
 'Sierra Leone',
 'South Africa',
 'South Sudan',
 'Sudan',
 'Tanzania',
 'Togo',
 'Tunisia',
 'Uganda',
 'Yemen',
 'Zaire',
 'Zambia',
 'Zimbabwe']


mineraldict = {"2":"alumina",
"3":"aluminium, primary",
"8":"antimony",
"6":"antimony,mine",
"11":"arsenic",
"9":"arsenic,white",
"12":"asbestos",
"14":"asbestos, unmanufactured",
"17":"barytes",
"1":"bauxite",
"5":"bauxite, alumina and aluminium",
"20":"bentonite and fuller's earth",
"160":"beryl",
"23":"bismuth",
"21":"bismuth,mine",
"161":"borates",
"26":"bromine",
"29":"cadmium",
"179":"cement",
"174":"cement clinker",
"175":"cement,finished",
"32":"chromium",
"30":"chromium ores and concentrates",
"35":"coal",
"39":"cobalt",
"36":"cobalt,mine",
"37":"cobalt,refined",
"44":"copper",
"40":"copper,mine",
"42":"copper,refined",
"41":"copper,smelter",
"47":"diamond",
"50":"diatomite",
"53":"feldspar",
"74":"ferro-alloys",
"56":"fluorspar",
"737":"gallium,primary",
"743":"gemstones",
"162":"germanium metal",
"59":"gold",
"57":"gold,mine",
"62":"graphite",
"65":"gypsum and plaster",
"740":"hafnium,refined",
"745":"helium",
"738":"indium,refinery",
"68":"iodine",
"71":"ironore",
"72":"iron,pig",
"76":"iron, steel and ferro-alloys",
"79":"kaolin",
"83":"lead",
"80":"lead,mine",
"81":"lead,refined",
"86":"lithium",
"84":"lithium minerals",
"87":"magnesite",
"89":"magnesite and magnesia",
"163":"magnesium metal, primary",
"92":"manganese",
"90":"manganeseore",
"95":"mercury",
"98":"mica",
"101":"molybdenum",
"99":"molybdenum,mine",
"107":"naturalgas",
"164":"nephelinesyenite",
"105":"nickel",
"102":"nickel,mine",
"103":"nickel,smelter/refinery",
"165":"perlite",
"109":"petroleum,crude",
"112":"phosphaterock",
"115":"platinumgroupmetals",
"113":"platinum group metals, mine",
"118":"potash",
"119":"rareearthminerals",
"736":"rareearthoxides",
"121":"rareearths",
"739":"rhenium",
"124":"salt",
"166":"selenium,refined",
"127":"sillimanite minerals",
"130":"silver",
"128":"silver,mine",
"172":"sodium carbonate,natural",
"73":"steel,crude",
"167":"strontiumminerals",
"133":"sulphurandpyrites",
"136":"talc",
"139":"tantalum and niobium",
"137":"tantalum and niobium minerals",
"168":"tellurium,refined",
"143":"tin",
"140":"tin,mine",
"141":"tin,smelter",
"146":"titanium",
"144":"titanium minerals",
"149":"tungsten",
"147":"tungsten,mine",
"169":"uranium",
"152":"vanadium",
"150":"vanadium,mine",
"170":"vermiculite",
"171":"wollastonite",
"156":"zinc",
"153":"zinc,mine",
"154":"zinc,slab",
"159":"zirconium",
"157":"zirconium minerals"}
